//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMPRESA_PK2Entities : DbContext
    {
        public EMPRESA_PK2Entities()
            : base("name=EMPRESA_PK2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_CANTON> TBL_CANTON { get; set; }
        public DbSet<TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICO { get; set; }
        public DbSet<TBL_PROVINCIA> TBL_PROVINCIA { get; set; }
        public DbSet<TBL_TARIFAAUTOBUS> TBL_TARIFAAUTOBUS { get; set; }
        public DbSet<TBL_ESTADOS> TBL_ESTADOS { get; set; }
        public DbSet<TBL_PERSONA> TBL_PERSONA { get; set; }
        public DbSet<TBL_ROLUSUARIO> TBL_ROLUSUARIO { get; set; }
        public DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
        public DbSet<TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACION { get; set; }
        public DbSet<TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICO { get; set; }
        public DbSet<TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS { get; set; }
        public DbSet<TBL_SOLICITUDVIATICOS> TBL_SOLICITUDVIATICOS { get; set; }
        public DbSet<TBL_DETALLEVIATICO> TBL_DETALLEVIATICO { get; set; }
    }
}
