//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EmpresaPK2Entities : DbContext
    {
        public EmpresaPK2Entities()
            : base("name=EmpresaPK2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_CANTON> TBL_CANTON { get; set; }
        public DbSet<TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICO { get; set; }
        public DbSet<TBL_PROVINCIA> TBL_PROVINCIA { get; set; }
        public DbSet<TBL_TARIFAAUTOBUS> TBL_TARIFAAUTOBUS { get; set; }
        public DbSet<TBL_ESTADOS> TBL_ESTADOS { get; set; }
        public DbSet<TBL_PERSONA> TBL_PERSONA { get; set; }
        public DbSet<TBL_ROLUSUARIO> TBL_ROLUSUARIO { get; set; }
        public DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
        public DbSet<TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACION { get; set; }
        public DbSet<TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICO { get; set; }
        public DbSet<TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS { get; set; }
        public DbSet<TBL_SOLICITUDVIATICOS> TBL_SOLICITUDVIATICOS { get; set; }
        public DbSet<TBL_DETALLEVIATICO> TBL_DETALLEVIATICO { get; set; }
    
        public virtual int SP_InsertarUsuario(string nOMBREUSUARIO, string cLAVEACCESO, Nullable<short> iD_Rol, Nullable<short> estadoUsuario, string email)
        {
            var nOMBREUSUARIOParameter = nOMBREUSUARIO != null ?
                new ObjectParameter("NOMBREUSUARIO", nOMBREUSUARIO) :
                new ObjectParameter("NOMBREUSUARIO", typeof(string));
    
            var cLAVEACCESOParameter = cLAVEACCESO != null ?
                new ObjectParameter("CLAVEACCESO", cLAVEACCESO) :
                new ObjectParameter("CLAVEACCESO", typeof(string));
    
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(short));
    
            var estadoUsuarioParameter = estadoUsuario.HasValue ?
                new ObjectParameter("EstadoUsuario", estadoUsuario) :
                new ObjectParameter("EstadoUsuario", typeof(short));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarUsuario", nOMBREUSUARIOParameter, cLAVEACCESOParameter, iD_RolParameter, estadoUsuarioParameter, emailParameter);
        }
    }
}
