//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CABECERAORDENVIATICO
    {
        public TBL_CABECERAORDENVIATICO()
        {
            this.TBL_CABECERALIQUIDACION = new HashSet<TBL_CABECERALIQUIDACION>();
            this.TBL_DETALLEVIATICO = new HashSet<TBL_DETALLEVIATICO>();
        }
    
        public int ID_ORDEN { get; set; }
        public int ID_SOLICITUD { get; set; }
        public int ID_LIQUIDACION { get; set; }
        public short ESTADOORDEN { get; set; }
        public System.DateTime FECHAORDEN { get; set; }
    
        public virtual TBL_ESTADOS TBL_ESTADOS { get; set; }
        public virtual ICollection<TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACION { get; set; }
        public virtual TBL_CABECERALIQUIDACION TBL_CABECERALIQUIDACION1 { get; set; }
        public virtual TBL_SOLICITUDVIATICOS TBL_SOLICITUDVIATICOS { get; set; }
        public virtual ICollection<TBL_DETALLEVIATICO> TBL_DETALLEVIATICO { get; set; }
    }
}
