//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLESOLICITUDVIATICOS
    {
        public TBL_DETALLESOLICITUDVIATICOS()
        {
            this.TBL_DETALLEVIATICO = new HashSet<TBL_DETALLEVIATICO>();
        }
    
        public int ID_DETALLE { get; set; }
        public int ID_SOLICITUD { get; set; }
        public short ID_PERSONA { get; set; }
        public short ID_MODTARIFA { get; set; }
        public short CANTIDADVIATICOS { get; set; }
        public System.DateTime FECHAVIATICOS { get; set; }
        public string CODIGORUTA { get; set; }
        public short CANTIDADPASAJE { get; set; }
    
        public virtual TBL_MODTARIFARIOVIATICO TBL_MODTARIFARIOVIATICO { get; set; }
        public virtual TBL_TARIFAAUTOBUS TBL_TARIFAAUTOBUS { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
        public virtual TBL_SOLICITUDVIATICOS TBL_SOLICITUDVIATICOS { get; set; }
        public virtual ICollection<TBL_DETALLEVIATICO> TBL_DETALLEVIATICO { get; set; }
    }
}
