//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CANTON
    {
        public TBL_CANTON()
        {
            this.TBL_MODTARIFARIOVIATICO = new HashSet<TBL_MODTARIFARIOVIATICO>();
        }
    
        public byte CODIGOCANTON { get; set; }
        public byte CODIGOPROVINCIA { get; set; }
        public string DESCRIPCIONPROVINCIA { get; set; }
    
        public virtual TBL_PROVINCIA TBL_PROVINCIA { get; set; }
        public virtual ICollection<TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICO { get; set; }
    }
}
