//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CANTON
    {
        public TBL_CANTON()
        {
            this.TBL_MODTARIFARIOVIATICO = new HashSet<TBL_MODTARIFARIOVIATICO>();
        }
    
        public byte CODIGOCANTON { get; set; }
        public byte CODIGOPROVINCIA { get; set; }
        public string DESCRIPCIONPROVINCIA { get; set; }
    
        public virtual TBL_PROVINCIA TBL_PROVINCIA { get; set; }
        public virtual ICollection<TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICO { get; set; }
    }
}
