//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ESTADOS
    {
        public TBL_ESTADOS()
        {
            this.TBL_MODTARIFARIOVIATICO = new HashSet<TBL_MODTARIFARIOVIATICO>();
            this.TBL_TARIFAAUTOBUS = new HashSet<TBL_TARIFAAUTOBUS>();
            this.TBL_CABECERALIQUIDACION = new HashSet<TBL_CABECERALIQUIDACION>();
            this.TBL_CABECERAORDENVIATICO = new HashSet<TBL_CABECERAORDENVIATICO>();
            this.TBL_SOLICITUDVIATICOS = new HashSet<TBL_SOLICITUDVIATICOS>();
            this.TBL_USUARIO = new HashSet<TBL_USUARIO>();
        }
    
        public short ID_CODIGO { get; set; }
        public string DESCODIGO { get; set; }
        public string ESTADOCODIGO { get; set; }
    
        public virtual ICollection<TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICO { get; set; }
        public virtual ICollection<TBL_TARIFAAUTOBUS> TBL_TARIFAAUTOBUS { get; set; }
        public virtual ICollection<TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACION { get; set; }
        public virtual ICollection<TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICO { get; set; }
        public virtual ICollection<TBL_SOLICITUDVIATICOS> TBL_SOLICITUDVIATICOS { get; set; }
        public virtual ICollection<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
