//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROLUSUARIO
    {
        public TBL_ROLUSUARIO()
        {
            this.TBL_USUARIO = new HashSet<TBL_USUARIO>();
        }
    
        public short ID_ROL { get; set; }
        public string DESCRPCIONROL { get; set; }
        public string ESTADOROL { get; set; }
    
        public virtual ICollection<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
