//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLESOLICITUDVIATICOS
    {
        public int ID_DETALLE { get; set; }
        public string ID_SOLICITUD { get; set; }
        public string ID_PERSONA { get; set; }
        public short CANTIDADVIATICOS { get; set; }
        public Nullable<short> CANTIDADDESAYUNO { get; set; }
        public Nullable<decimal> MONTODESAYUNO { get; set; }
        public Nullable<short> CANTIDADALMUERZO { get; set; }
        public Nullable<decimal> MONTOALMUERZO { get; set; }
        public Nullable<short> CANTIDADCENA { get; set; }
        public Nullable<decimal> MONTOCENA { get; set; }
        public Nullable<short> CANTIDADPASAJE { get; set; }
        public Nullable<decimal> MONTOPASAJE { get; set; }
        public string CODIGORUTA { get; set; }
        public Nullable<short> LOCALIDADHOSPEDAJE { get; set; }
        public Nullable<decimal> MONTOHOSPEDAJE { get; set; }
    
        public virtual TBL_MODTARIFARIOVIATICO TBL_MODTARIFARIOVIATICO { get; set; }
        public virtual TBL_TARIFAAUTOBUS TBL_TARIFAAUTOBUS { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
        public virtual TBL_SOLICITUDVIATICOS TBL_SOLICITUDVIATICOS { get; set; }
    }
}
