//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CABECERAORDENVIATICO
    {
        public TBL_CABECERAORDENVIATICO()
        {
            this.TBL_CABECERALIQUIDACION = new HashSet<TBL_CABECERALIQUIDACION>();
        }
    
        public int ID_ORDEN { get; set; }
        public string ID_SOLICITUD { get; set; }
        public short ESTADOORDEN { get; set; }
        public System.DateTime FECHAORDEN { get; set; }
    
        public virtual TBL_ESTADOS TBL_ESTADOS { get; set; }
        public virtual ICollection<TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACION { get; set; }
        public virtual TBL_SOLICITUDVIATICOS TBL_SOLICITUDVIATICOS { get; set; }
    }
}
