//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SOLICITUDVIATICOS
    {
        public TBL_SOLICITUDVIATICOS()
        {
            this.TBL_CABECERAORDENVIATICO = new HashSet<TBL_CABECERAORDENVIATICO>();
            this.TBL_DETALLESOLICITUDVIATICOS = new HashSet<TBL_DETALLESOLICITUDVIATICOS>();
        }
    
        public int ID_SOLICITUD { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public System.DateTime FECHASALIDA { get; set; }
        public System.DateTime FECHAREGRESO { get; set; }
        public short ESTADOSOLICITUD { get; set; }
        public string JUSTIFICACION { get; set; }
        public string DESTINO { get; set; }
        public System.TimeSpan HORAREGRESO { get; set; }
        public System.TimeSpan HORASALIDA { get; set; }
    
        public virtual TBL_ESTADOS TBL_ESTADOS { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        public virtual ICollection<TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICO { get; set; }
        public virtual ICollection<TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS { get; set; }
    }
}
