//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLEVIATICO
    {
        public int ID_DETALLE { get; set; }
        public int ID_ORDEN { get; set; }
        public short CANTIDADDESAYUNO { get; set; }
        public decimal MONTODESAYUNO { get; set; }
        public short CANTIDADALMUERZO { get; set; }
        public decimal MONTOALMUERZO { get; set; }
        public short CANTIDADCENA { get; set; }
        public decimal MONTOCENA { get; set; }
        public short CANTIDADPASAJE { get; set; }
        public decimal MONTOPASAJE { get; set; }
    
        public virtual TBL_CABECERAORDENVIATICO TBL_CABECERAORDENVIATICO { get; set; }
        public virtual TBL_DETALLESOLICITUDVIATICOS TBL_DETALLESOLICITUDVIATICOS { get; set; }
    }
}
