//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLEVIATICO
    {
        public int ID_DETALLE { get; set; }
        public int ID_ORDEN { get; set; }
        public short CANTIDADDESAYUNO { get; set; }
        public decimal MONTODESAYUNO { get; set; }
        public short CANTIDADALMUERZO { get; set; }
        public decimal MONTOALMUERZO { get; set; }
        public short CANTIDADCENA { get; set; }
        public decimal MONTOCENA { get; set; }
        public short CANTIDADPASAJE { get; set; }
        public decimal MONTOPASAJE { get; set; }
    
        public virtual TBL_CABECERAORDENVIATICO TBL_CABECERAORDENVIATICO { get; set; }
        public virtual TBL_DETALLESOLICITUDVIATICOS TBL_DETALLESOLICITUDVIATICOS { get; set; }
    }
}
