//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MODTARIFARIOVIATICO
    {
        public TBL_MODTARIFARIOVIATICO()
        {
            this.TBL_DETALLESOLICITUDVIATICOS = new HashSet<TBL_DETALLESOLICITUDVIATICOS>();
        }
    
        public short ID_MODTARIFA { get; set; }
        public byte CODIGOPROVINCIA { get; set; }
        public byte CODIGOCANTON { get; set; }
        public string TIPOTARIFA { get; set; }
        public System.DateTime FECHATARIFA { get; set; }
        public decimal MONTOTARIFA { get; set; }
        public short ESTADOTARIFA { get; set; }
        public string LOCALIDAD { get; set; }
    
        public virtual TBL_CANTON TBL_CANTON { get; set; }
        public virtual ICollection<TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS { get; set; }
        public virtual TBL_ESTADOS TBL_ESTADOS { get; set; }
        public virtual TBL_PROVINCIA TBL_PROVINCIA { get; set; }
    }
}
