//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONA
    {
        public TBL_PERSONA()
        {
            this.TBL_DETALLESOLICITUDVIATICOS = new HashSet<TBL_DETALLESOLICITUDVIATICOS>();
        }
    
        public string ID_PERSONA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string NOMBREUSUARIO { get; set; }
    
        public virtual ICollection<TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
