//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascaronPrograIV.WCFSolicitud {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFSolicitud.ISolicitud")]
    public interface ISolicitud {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/GuardarSolicitud", ReplyAction="http://tempuri.org/ISolicitud/GuardarSolicitudResponse")]
        bool GuardarSolicitud(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/GuardarSolicitud", ReplyAction="http://tempuri.org/ISolicitud/GuardarSolicitudResponse")]
        System.Threading.Tasks.Task<bool> GuardarSolicitudAsync(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarSolicitudes", ReplyAction="http://tempuri.org/ISolicitud/ListarSolicitudesResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_FUNCIONARIO_Result> ListarSolicitudes(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarSolicitudes", ReplyAction="http://tempuri.org/ISolicitud/ListarSolicitudesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_FUNCIONARIO_Result>> ListarSolicitudesAsync(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitudChannel : CascaronPrograIV.WCFSolicitud.ISolicitud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitudClient : System.ServiceModel.ClientBase<CascaronPrograIV.WCFSolicitud.ISolicitud>, CascaronPrograIV.WCFSolicitud.ISolicitud {
        
        public SolicitudClient() {
        }
        
        public SolicitudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GuardarSolicitud(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud) {
            return base.Channel.GuardarSolicitud(Obj_Solicitud);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarSolicitudAsync(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud) {
            return base.Channel.GuardarSolicitudAsync(Obj_Solicitud);
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_FUNCIONARIO_Result> ListarSolicitudes(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud) {
            return base.Channel.ListarSolicitudes(Obj_Solicitud);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_FUNCIONARIO_Result>> ListarSolicitudesAsync(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud) {
            return base.Channel.ListarSolicitudesAsync(Obj_Solicitud);
        }
    }
}
