//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascaronPrograIV.WCFSolicitud {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFSolicitud.ISolicitud")]
    public interface ISolicitud {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/GuardarSolicitudDetalle", ReplyAction="http://tempuri.org/ISolicitud/GuardarSolicitudDetalleResponse")]
        bool GuardarSolicitudDetalle(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud, System.Collections.Generic.List<Entidades.TBL_DETALLESOLICITUDVIATICOS> Obj_SolicitudDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/GuardarSolicitudDetalle", ReplyAction="http://tempuri.org/ISolicitud/GuardarSolicitudDetalleResponse")]
        System.Threading.Tasks.Task<bool> GuardarSolicitudDetalleAsync(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud, System.Collections.Generic.List<Entidades.TBL_DETALLESOLICITUDVIATICOS> Obj_SolicitudDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarSolicitudes", ReplyAction="http://tempuri.org/ISolicitud/ListarSolicitudesResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_FUNCIONARIO_Result> ListarSolicitudes(string sNombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarSolicitudes", ReplyAction="http://tempuri.org/ISolicitud/ListarSolicitudesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_FUNCIONARIO_Result>> ListarSolicitudesAsync(string sNombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarLocalidad", ReplyAction="http://tempuri.org/ISolicitud/ListarLocalidadResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTAR_LOCALIDAD_Result> ListarLocalidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarLocalidad", ReplyAction="http://tempuri.org/ISolicitud/ListarLocalidadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_LOCALIDAD_Result>> ListarLocalidadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarRutas", ReplyAction="http://tempuri.org/ISolicitud/ListarRutasResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTAR_RUTAS_Result> ListarRutas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarRutas", ReplyAction="http://tempuri.org/ISolicitud/ListarRutasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_RUTAS_Result>> ListarRutasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarPersonas", ReplyAction="http://tempuri.org/ISolicitud/ListarPersonasResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTAR_PERSONAS_Result> ListarPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarPersonas", ReplyAction="http://tempuri.org/ISolicitud/ListarPersonasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_PERSONAS_Result>> ListarPersonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/MontoRuta", ReplyAction="http://tempuri.org/ISolicitud/MontoRutaResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTARMONTORUTA_Result> MontoRuta(string sIdRuta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/MontoRuta", ReplyAction="http://tempuri.org/ISolicitud/MontoRutaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTARMONTORUTA_Result>> MontoRutaAsync(string sIdRuta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/Montos", ReplyAction="http://tempuri.org/ISolicitud/MontosResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTARMONTOS_Result> Montos(int iIdHospedaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/Montos", ReplyAction="http://tempuri.org/ISolicitud/MontosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTARMONTOS_Result>> MontosAsync(int iIdHospedaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarSolcitudesActualizar", ReplyAction="http://tempuri.org/ISolicitud/ListarSolcitudesActualizarResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_UPDATE_Result> ListarSolcitudesActualizar(string sUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarSolcitudesActualizar", ReplyAction="http://tempuri.org/ISolicitud/ListarSolcitudesActualizarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_UPDATE_Result>> ListarSolcitudesActualizarAsync(string sUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarSolicitudesVerificar", ReplyAction="http://tempuri.org/ISolicitud/ListarSolicitudesVerificarResponse")]
        System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_VERIFICAR_Result> ListarSolicitudesVerificar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/ListarSolicitudesVerificar", ReplyAction="http://tempuri.org/ISolicitud/ListarSolicitudesVerificarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_VERIFICAR_Result>> ListarSolicitudesVerificarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/VerificarSolicitud", ReplyAction="http://tempuri.org/ISolicitud/VerificarSolicitudResponse")]
        bool VerificarSolicitud(string sIdSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitud/VerificarSolicitud", ReplyAction="http://tempuri.org/ISolicitud/VerificarSolicitudResponse")]
        System.Threading.Tasks.Task<bool> VerificarSolicitudAsync(string sIdSolicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitudChannel : CascaronPrograIV.WCFSolicitud.ISolicitud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitudClient : System.ServiceModel.ClientBase<CascaronPrograIV.WCFSolicitud.ISolicitud>, CascaronPrograIV.WCFSolicitud.ISolicitud {
        
        public SolicitudClient() {
        }
        
        public SolicitudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GuardarSolicitudDetalle(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud, System.Collections.Generic.List<Entidades.TBL_DETALLESOLICITUDVIATICOS> Obj_SolicitudDetalle) {
            return base.Channel.GuardarSolicitudDetalle(Obj_Solicitud, Obj_SolicitudDetalle);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarSolicitudDetalleAsync(Entidades.TBL_SOLICITUDVIATICOS Obj_Solicitud, System.Collections.Generic.List<Entidades.TBL_DETALLESOLICITUDVIATICOS> Obj_SolicitudDetalle) {
            return base.Channel.GuardarSolicitudDetalleAsync(Obj_Solicitud, Obj_SolicitudDetalle);
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_FUNCIONARIO_Result> ListarSolicitudes(string sNombreUsuario) {
            return base.Channel.ListarSolicitudes(sNombreUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_FUNCIONARIO_Result>> ListarSolicitudesAsync(string sNombreUsuario) {
            return base.Channel.ListarSolicitudesAsync(sNombreUsuario);
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTAR_LOCALIDAD_Result> ListarLocalidad() {
            return base.Channel.ListarLocalidad();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_LOCALIDAD_Result>> ListarLocalidadAsync() {
            return base.Channel.ListarLocalidadAsync();
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTAR_RUTAS_Result> ListarRutas() {
            return base.Channel.ListarRutas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_RUTAS_Result>> ListarRutasAsync() {
            return base.Channel.ListarRutasAsync();
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTAR_PERSONAS_Result> ListarPersonas() {
            return base.Channel.ListarPersonas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_PERSONAS_Result>> ListarPersonasAsync() {
            return base.Channel.ListarPersonasAsync();
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTARMONTORUTA_Result> MontoRuta(string sIdRuta) {
            return base.Channel.MontoRuta(sIdRuta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTARMONTORUTA_Result>> MontoRutaAsync(string sIdRuta) {
            return base.Channel.MontoRutaAsync(sIdRuta);
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTARMONTOS_Result> Montos(int iIdHospedaje) {
            return base.Channel.Montos(iIdHospedaje);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTARMONTOS_Result>> MontosAsync(int iIdHospedaje) {
            return base.Channel.MontosAsync(iIdHospedaje);
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_UPDATE_Result> ListarSolcitudesActualizar(string sUsuario) {
            return base.Channel.ListarSolcitudesActualizar(sUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_UPDATE_Result>> ListarSolcitudesActualizarAsync(string sUsuario) {
            return base.Channel.ListarSolcitudesActualizarAsync(sUsuario);
        }
        
        public System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_VERIFICAR_Result> ListarSolicitudesVerificar() {
            return base.Channel.ListarSolicitudesVerificar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_LISTAR_SOLICITUDES_VERIFICAR_Result>> ListarSolicitudesVerificarAsync() {
            return base.Channel.ListarSolicitudesVerificarAsync();
        }
        
        public bool VerificarSolicitud(string sIdSolicitud) {
            return base.Channel.VerificarSolicitud(sIdSolicitud);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarSolicitudAsync(string sIdSolicitud) {
            return base.Channel.VerificarSolicitudAsync(sIdSolicitud);
        }
    }
}
