//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascaronPrograIV.WCFServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_ROLUSUARIO", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_ROLUSUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRPCIONROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_ROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_USUARIO> TBL_USUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRPCIONROL {
            get {
                return this.DESCRPCIONROLField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRPCIONROLField, value) != true)) {
                    this.DESCRPCIONROLField = value;
                    this.RaisePropertyChanged("DESCRPCIONROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADOROL {
            get {
                return this.ESTADOROLField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOROLField, value) != true)) {
                    this.ESTADOROLField = value;
                    this.RaisePropertyChanged("ESTADOROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_ROL {
            get {
                return this.ID_ROLField;
            }
            set {
                if ((this.ID_ROLField.Equals(value) != true)) {
                    this.ID_ROLField = value;
                    this.RaisePropertyChanged("ID_ROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_USUARIO> TBL_USUARIO {
            get {
                return this.TBL_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_USUARIOField, value) != true)) {
                    this.TBL_USUARIOField = value;
                    this.RaisePropertyChanged("TBL_USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_USUARIO", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLAVEACCESOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADOUSARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_ROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROLUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_PERSONA> TBL_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_ROLUSUARIO TBL_ROLUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_SOLICITUDVIATICOS> TBL_SOLICITUDVIATICOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLAVEACCESO {
            get {
                return this.CLAVEACCESOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLAVEACCESOField, value) != true)) {
                    this.CLAVEACCESOField = value;
                    this.RaisePropertyChanged("CLAVEACCESO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADOUSARIO {
            get {
                return this.ESTADOUSARIOField;
            }
            set {
                if ((this.ESTADOUSARIOField.Equals(value) != true)) {
                    this.ESTADOUSARIOField = value;
                    this.RaisePropertyChanged("ESTADOUSARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_ROL {
            get {
                return this.ID_ROLField;
            }
            set {
                if ((this.ID_ROLField.Equals(value) != true)) {
                    this.ID_ROLField = value;
                    this.RaisePropertyChanged("ID_ROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBREUSUARIO {
            get {
                return this.NOMBREUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREUSUARIOField, value) != true)) {
                    this.NOMBREUSUARIOField = value;
                    this.RaisePropertyChanged("NOMBREUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROLUSUARIO {
            get {
                return this.ROLUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.ROLUSUARIOField, value) != true)) {
                    this.ROLUSUARIOField = value;
                    this.RaisePropertyChanged("ROLUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOS {
            get {
                return this.TBL_ESTADOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_ESTADOSField, value) != true)) {
                    this.TBL_ESTADOSField = value;
                    this.RaisePropertyChanged("TBL_ESTADOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_PERSONA> TBL_PERSONA {
            get {
                return this.TBL_PERSONAField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_PERSONAField, value) != true)) {
                    this.TBL_PERSONAField = value;
                    this.RaisePropertyChanged("TBL_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_ROLUSUARIO TBL_ROLUSUARIO {
            get {
                return this.TBL_ROLUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_ROLUSUARIOField, value) != true)) {
                    this.TBL_ROLUSUARIOField = value;
                    this.RaisePropertyChanged("TBL_ROLUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_SOLICITUDVIATICOS> TBL_SOLICITUDVIATICOS {
            get {
                return this.TBL_SOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_SOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_SOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_SOLICITUDVIATICOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_ESTADOS", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_ESTADOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOCODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_SOLICITUDVIATICOS> TBL_SOLICITUDVIATICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_TARIFAAUTOBUS> TBL_TARIFAAUTOBUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_USUARIO> TBL_USUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCODIGO {
            get {
                return this.DESCODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCODIGOField, value) != true)) {
                    this.DESCODIGOField = value;
                    this.RaisePropertyChanged("DESCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADOCODIGO {
            get {
                return this.ESTADOCODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOCODIGOField, value) != true)) {
                    this.ESTADOCODIGOField = value;
                    this.RaisePropertyChanged("ESTADOCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_CODIGO {
            get {
                return this.ID_CODIGOField;
            }
            set {
                if ((this.ID_CODIGOField.Equals(value) != true)) {
                    this.ID_CODIGOField = value;
                    this.RaisePropertyChanged("ID_CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACION {
            get {
                return this.TBL_CABECERALIQUIDACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CABECERALIQUIDACIONField, value) != true)) {
                    this.TBL_CABECERALIQUIDACIONField = value;
                    this.RaisePropertyChanged("TBL_CABECERALIQUIDACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICO {
            get {
                return this.TBL_CABECERAORDENVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CABECERAORDENVIATICOField, value) != true)) {
                    this.TBL_CABECERAORDENVIATICOField = value;
                    this.RaisePropertyChanged("TBL_CABECERAORDENVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICO {
            get {
                return this.TBL_MODTARIFARIOVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_MODTARIFARIOVIATICOField, value) != true)) {
                    this.TBL_MODTARIFARIOVIATICOField = value;
                    this.RaisePropertyChanged("TBL_MODTARIFARIOVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_SOLICITUDVIATICOS> TBL_SOLICITUDVIATICOS {
            get {
                return this.TBL_SOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_SOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_SOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_SOLICITUDVIATICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_TARIFAAUTOBUS> TBL_TARIFAAUTOBUS {
            get {
                return this.TBL_TARIFAAUTOBUSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_TARIFAAUTOBUSField, value) != true)) {
                    this.TBL_TARIFAAUTOBUSField = value;
                    this.RaisePropertyChanged("TBL_TARIFAAUTOBUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_USUARIO> TBL_USUARIO {
            get {
                return this.TBL_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_USUARIOField, value) != true)) {
                    this.TBL_USUARIOField = value;
                    this.RaisePropertyChanged("TBL_USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_PERSONA", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_PERSONA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRIMERAPELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEGUNDOAPELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_USUARIO TBL_USUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBREUSUARIO {
            get {
                return this.NOMBREUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREUSUARIOField, value) != true)) {
                    this.NOMBREUSUARIOField = value;
                    this.RaisePropertyChanged("NOMBREUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRIMERAPELLIDO {
            get {
                return this.PRIMERAPELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRIMERAPELLIDOField, value) != true)) {
                    this.PRIMERAPELLIDOField = value;
                    this.RaisePropertyChanged("PRIMERAPELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEGUNDOAPELLIDO {
            get {
                return this.SEGUNDOAPELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.SEGUNDOAPELLIDOField, value) != true)) {
                    this.SEGUNDOAPELLIDOField = value;
                    this.RaisePropertyChanged("SEGUNDOAPELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS {
            get {
                return this.TBL_DETALLESOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_DETALLESOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_DETALLESOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_DETALLESOLICITUDVIATICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_USUARIO TBL_USUARIO {
            get {
                return this.TBL_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_USUARIOField, value) != true)) {
                    this.TBL_USUARIOField = value;
                    this.RaisePropertyChanged("TBL_USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_SOLICITUDVIATICOS", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_SOLICITUDVIATICOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESTINOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADOSOLICITUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHACREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAREGRESOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHASALIDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HORAREGRESOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HORASALIDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_SOLICITUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JUSTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_USUARIO TBL_USUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESTINO {
            get {
                return this.DESTINOField;
            }
            set {
                if ((object.ReferenceEquals(this.DESTINOField, value) != true)) {
                    this.DESTINOField = value;
                    this.RaisePropertyChanged("DESTINO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADOSOLICITUD {
            get {
                return this.ESTADOSOLICITUDField;
            }
            set {
                if ((this.ESTADOSOLICITUDField.Equals(value) != true)) {
                    this.ESTADOSOLICITUDField = value;
                    this.RaisePropertyChanged("ESTADOSOLICITUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHACREACION {
            get {
                return this.FECHACREACIONField;
            }
            set {
                if ((this.FECHACREACIONField.Equals(value) != true)) {
                    this.FECHACREACIONField = value;
                    this.RaisePropertyChanged("FECHACREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAREGRESO {
            get {
                return this.FECHAREGRESOField;
            }
            set {
                if ((this.FECHAREGRESOField.Equals(value) != true)) {
                    this.FECHAREGRESOField = value;
                    this.RaisePropertyChanged("FECHAREGRESO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHASALIDA {
            get {
                return this.FECHASALIDAField;
            }
            set {
                if ((this.FECHASALIDAField.Equals(value) != true)) {
                    this.FECHASALIDAField = value;
                    this.RaisePropertyChanged("FECHASALIDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HORAREGRESO {
            get {
                return this.HORAREGRESOField;
            }
            set {
                if ((this.HORAREGRESOField.Equals(value) != true)) {
                    this.HORAREGRESOField = value;
                    this.RaisePropertyChanged("HORAREGRESO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HORASALIDA {
            get {
                return this.HORASALIDAField;
            }
            set {
                if ((this.HORASALIDAField.Equals(value) != true)) {
                    this.HORASALIDAField = value;
                    this.RaisePropertyChanged("HORASALIDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SOLICITUD {
            get {
                return this.ID_SOLICITUDField;
            }
            set {
                if ((this.ID_SOLICITUDField.Equals(value) != true)) {
                    this.ID_SOLICITUDField = value;
                    this.RaisePropertyChanged("ID_SOLICITUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JUSTIFICACION {
            get {
                return this.JUSTIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.JUSTIFICACIONField, value) != true)) {
                    this.JUSTIFICACIONField = value;
                    this.RaisePropertyChanged("JUSTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBREUSUARIO {
            get {
                return this.NOMBREUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREUSUARIOField, value) != true)) {
                    this.NOMBREUSUARIOField = value;
                    this.RaisePropertyChanged("NOMBREUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICO {
            get {
                return this.TBL_CABECERAORDENVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CABECERAORDENVIATICOField, value) != true)) {
                    this.TBL_CABECERAORDENVIATICOField = value;
                    this.RaisePropertyChanged("TBL_CABECERAORDENVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS {
            get {
                return this.TBL_DETALLESOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_DETALLESOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_DETALLESOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_DETALLESOLICITUDVIATICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOS {
            get {
                return this.TBL_ESTADOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_ESTADOSField, value) != true)) {
                    this.TBL_ESTADOSField = value;
                    this.RaisePropertyChanged("TBL_ESTADOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_USUARIO TBL_USUARIO {
            get {
                return this.TBL_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_USUARIOField, value) != true)) {
                    this.TBL_USUARIOField = value;
                    this.RaisePropertyChanged("TBL_USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_CABECERALIQUIDACION", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_CABECERALIQUIDACION : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADOLIQUIDACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHALIQUIDACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_LIQUIDACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ORDENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTOALMUERZOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTOCENAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTODESAYUNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTOHOSPEDAJEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTOPASAJEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO TBL_CABECERAORDENVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICO1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADOLIQUIDACION {
            get {
                return this.ESTADOLIQUIDACIONField;
            }
            set {
                if ((this.ESTADOLIQUIDACIONField.Equals(value) != true)) {
                    this.ESTADOLIQUIDACIONField = value;
                    this.RaisePropertyChanged("ESTADOLIQUIDACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHALIQUIDACION {
            get {
                return this.FECHALIQUIDACIONField;
            }
            set {
                if ((this.FECHALIQUIDACIONField.Equals(value) != true)) {
                    this.FECHALIQUIDACIONField = value;
                    this.RaisePropertyChanged("FECHALIQUIDACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LIQUIDACION {
            get {
                return this.ID_LIQUIDACIONField;
            }
            set {
                if ((this.ID_LIQUIDACIONField.Equals(value) != true)) {
                    this.ID_LIQUIDACIONField = value;
                    this.RaisePropertyChanged("ID_LIQUIDACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ORDEN {
            get {
                return this.ID_ORDENField;
            }
            set {
                if ((this.ID_ORDENField.Equals(value) != true)) {
                    this.ID_ORDENField = value;
                    this.RaisePropertyChanged("ID_ORDEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTOALMUERZO {
            get {
                return this.MONTOALMUERZOField;
            }
            set {
                if ((this.MONTOALMUERZOField.Equals(value) != true)) {
                    this.MONTOALMUERZOField = value;
                    this.RaisePropertyChanged("MONTOALMUERZO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTOCENA {
            get {
                return this.MONTOCENAField;
            }
            set {
                if ((this.MONTOCENAField.Equals(value) != true)) {
                    this.MONTOCENAField = value;
                    this.RaisePropertyChanged("MONTOCENA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTODESAYUNO {
            get {
                return this.MONTODESAYUNOField;
            }
            set {
                if ((this.MONTODESAYUNOField.Equals(value) != true)) {
                    this.MONTODESAYUNOField = value;
                    this.RaisePropertyChanged("MONTODESAYUNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTOHOSPEDAJE {
            get {
                return this.MONTOHOSPEDAJEField;
            }
            set {
                if ((this.MONTOHOSPEDAJEField.Equals(value) != true)) {
                    this.MONTOHOSPEDAJEField = value;
                    this.RaisePropertyChanged("MONTOHOSPEDAJE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTOPASAJE {
            get {
                return this.MONTOPASAJEField;
            }
            set {
                if ((this.MONTOPASAJEField.Equals(value) != true)) {
                    this.MONTOPASAJEField = value;
                    this.RaisePropertyChanged("MONTOPASAJE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO TBL_CABECERAORDENVIATICO {
            get {
                return this.TBL_CABECERAORDENVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CABECERAORDENVIATICOField, value) != true)) {
                    this.TBL_CABECERAORDENVIATICOField = value;
                    this.RaisePropertyChanged("TBL_CABECERAORDENVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO> TBL_CABECERAORDENVIATICO1 {
            get {
                return this.TBL_CABECERAORDENVIATICO1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CABECERAORDENVIATICO1Field, value) != true)) {
                    this.TBL_CABECERAORDENVIATICO1Field = value;
                    this.RaisePropertyChanged("TBL_CABECERAORDENVIATICO1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOS {
            get {
                return this.TBL_ESTADOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_ESTADOSField, value) != true)) {
                    this.TBL_ESTADOSField = value;
                    this.RaisePropertyChanged("TBL_ESTADOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_CABECERAORDENVIATICO", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_CABECERAORDENVIATICO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADOORDENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAORDENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_LIQUIDACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ORDENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_SOLICITUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_CABECERALIQUIDACION TBL_CABECERALIQUIDACION1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLEVIATICO> TBL_DETALLEVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_SOLICITUDVIATICOS TBL_SOLICITUDVIATICOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADOORDEN {
            get {
                return this.ESTADOORDENField;
            }
            set {
                if ((this.ESTADOORDENField.Equals(value) != true)) {
                    this.ESTADOORDENField = value;
                    this.RaisePropertyChanged("ESTADOORDEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAORDEN {
            get {
                return this.FECHAORDENField;
            }
            set {
                if ((this.FECHAORDENField.Equals(value) != true)) {
                    this.FECHAORDENField = value;
                    this.RaisePropertyChanged("FECHAORDEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LIQUIDACION {
            get {
                return this.ID_LIQUIDACIONField;
            }
            set {
                if ((this.ID_LIQUIDACIONField.Equals(value) != true)) {
                    this.ID_LIQUIDACIONField = value;
                    this.RaisePropertyChanged("ID_LIQUIDACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ORDEN {
            get {
                return this.ID_ORDENField;
            }
            set {
                if ((this.ID_ORDENField.Equals(value) != true)) {
                    this.ID_ORDENField = value;
                    this.RaisePropertyChanged("ID_ORDEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SOLICITUD {
            get {
                return this.ID_SOLICITUDField;
            }
            set {
                if ((this.ID_SOLICITUDField.Equals(value) != true)) {
                    this.ID_SOLICITUDField = value;
                    this.RaisePropertyChanged("ID_SOLICITUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CABECERALIQUIDACION> TBL_CABECERALIQUIDACION {
            get {
                return this.TBL_CABECERALIQUIDACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CABECERALIQUIDACIONField, value) != true)) {
                    this.TBL_CABECERALIQUIDACIONField = value;
                    this.RaisePropertyChanged("TBL_CABECERALIQUIDACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_CABECERALIQUIDACION TBL_CABECERALIQUIDACION1 {
            get {
                return this.TBL_CABECERALIQUIDACION1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CABECERALIQUIDACION1Field, value) != true)) {
                    this.TBL_CABECERALIQUIDACION1Field = value;
                    this.RaisePropertyChanged("TBL_CABECERALIQUIDACION1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLEVIATICO> TBL_DETALLEVIATICO {
            get {
                return this.TBL_DETALLEVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_DETALLEVIATICOField, value) != true)) {
                    this.TBL_DETALLEVIATICOField = value;
                    this.RaisePropertyChanged("TBL_DETALLEVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOS {
            get {
                return this.TBL_ESTADOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_ESTADOSField, value) != true)) {
                    this.TBL_ESTADOSField = value;
                    this.RaisePropertyChanged("TBL_ESTADOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_SOLICITUDVIATICOS TBL_SOLICITUDVIATICOS {
            get {
                return this.TBL_SOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_SOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_SOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_SOLICITUDVIATICOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_MODTARIFARIOVIATICO", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_MODTARIFARIOVIATICO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CODIGOCANTONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CODIGOPROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADOTARIFAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHATARIFAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_MODTARIFAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOCALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTOTARIFAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_CANTON TBL_CANTONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_PROVINCIA TBL_PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOTARIFAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CODIGOCANTON {
            get {
                return this.CODIGOCANTONField;
            }
            set {
                if ((this.CODIGOCANTONField.Equals(value) != true)) {
                    this.CODIGOCANTONField = value;
                    this.RaisePropertyChanged("CODIGOCANTON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CODIGOPROVINCIA {
            get {
                return this.CODIGOPROVINCIAField;
            }
            set {
                if ((this.CODIGOPROVINCIAField.Equals(value) != true)) {
                    this.CODIGOPROVINCIAField = value;
                    this.RaisePropertyChanged("CODIGOPROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADOTARIFA {
            get {
                return this.ESTADOTARIFAField;
            }
            set {
                if ((this.ESTADOTARIFAField.Equals(value) != true)) {
                    this.ESTADOTARIFAField = value;
                    this.RaisePropertyChanged("ESTADOTARIFA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHATARIFA {
            get {
                return this.FECHATARIFAField;
            }
            set {
                if ((this.FECHATARIFAField.Equals(value) != true)) {
                    this.FECHATARIFAField = value;
                    this.RaisePropertyChanged("FECHATARIFA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_MODTARIFA {
            get {
                return this.ID_MODTARIFAField;
            }
            set {
                if ((this.ID_MODTARIFAField.Equals(value) != true)) {
                    this.ID_MODTARIFAField = value;
                    this.RaisePropertyChanged("ID_MODTARIFA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOCALIDAD {
            get {
                return this.LOCALIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.LOCALIDADField, value) != true)) {
                    this.LOCALIDADField = value;
                    this.RaisePropertyChanged("LOCALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTOTARIFA {
            get {
                return this.MONTOTARIFAField;
            }
            set {
                if ((this.MONTOTARIFAField.Equals(value) != true)) {
                    this.MONTOTARIFAField = value;
                    this.RaisePropertyChanged("MONTOTARIFA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_CANTON TBL_CANTON {
            get {
                return this.TBL_CANTONField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CANTONField, value) != true)) {
                    this.TBL_CANTONField = value;
                    this.RaisePropertyChanged("TBL_CANTON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS {
            get {
                return this.TBL_DETALLESOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_DETALLESOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_DETALLESOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_DETALLESOLICITUDVIATICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOS {
            get {
                return this.TBL_ESTADOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_ESTADOSField, value) != true)) {
                    this.TBL_ESTADOSField = value;
                    this.RaisePropertyChanged("TBL_ESTADOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_PROVINCIA TBL_PROVINCIA {
            get {
                return this.TBL_PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_PROVINCIAField, value) != true)) {
                    this.TBL_PROVINCIAField = value;
                    this.RaisePropertyChanged("TBL_PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPOTARIFA {
            get {
                return this.TIPOTARIFAField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOTARIFAField, value) != true)) {
                    this.TIPOTARIFAField = value;
                    this.RaisePropertyChanged("TIPOTARIFA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_TARIFAAUTOBUS", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_TARIFAAUTOBUS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CODIGOPROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGORUTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONRUTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ESTADORUTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAVIGENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TARIFAREGISTRADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_PROVINCIA TBL_PROVINCIAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CODIGOPROVINCIA {
            get {
                return this.CODIGOPROVINCIAField;
            }
            set {
                if ((this.CODIGOPROVINCIAField.Equals(value) != true)) {
                    this.CODIGOPROVINCIAField = value;
                    this.RaisePropertyChanged("CODIGOPROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGORUTA {
            get {
                return this.CODIGORUTAField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGORUTAField, value) != true)) {
                    this.CODIGORUTAField = value;
                    this.RaisePropertyChanged("CODIGORUTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCIONRUTA {
            get {
                return this.DESCRIPCIONRUTAField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONRUTAField, value) != true)) {
                    this.DESCRIPCIONRUTAField = value;
                    this.RaisePropertyChanged("DESCRIPCIONRUTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ESTADORUTA {
            get {
                return this.ESTADORUTAField;
            }
            set {
                if ((this.ESTADORUTAField.Equals(value) != true)) {
                    this.ESTADORUTAField = value;
                    this.RaisePropertyChanged("ESTADORUTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAVIGENCIA {
            get {
                return this.FECHAVIGENCIAField;
            }
            set {
                if ((this.FECHAVIGENCIAField.Equals(value) != true)) {
                    this.FECHAVIGENCIAField = value;
                    this.RaisePropertyChanged("FECHAVIGENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TARIFAREGISTRADA {
            get {
                return this.TARIFAREGISTRADAField;
            }
            set {
                if ((this.TARIFAREGISTRADAField.Equals(value) != true)) {
                    this.TARIFAREGISTRADAField = value;
                    this.RaisePropertyChanged("TARIFAREGISTRADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS> TBL_DETALLESOLICITUDVIATICOS {
            get {
                return this.TBL_DETALLESOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_DETALLESOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_DETALLESOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_DETALLESOLICITUDVIATICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_ESTADOS TBL_ESTADOS {
            get {
                return this.TBL_ESTADOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_ESTADOSField, value) != true)) {
                    this.TBL_ESTADOSField = value;
                    this.RaisePropertyChanged("TBL_ESTADOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_PROVINCIA TBL_PROVINCIA {
            get {
                return this.TBL_PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_PROVINCIAField, value) != true)) {
                    this.TBL_PROVINCIAField = value;
                    this.RaisePropertyChanged("TBL_PROVINCIA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_DETALLEVIATICO", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_DETALLEVIATICO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CANTIDADALMUERZOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CANTIDADCENAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CANTIDADDESAYUNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CANTIDADPASAJEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ORDENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTOALMUERZOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTOCENAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTODESAYUNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTOPASAJEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO TBL_CABECERAORDENVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS TBL_DETALLESOLICITUDVIATICOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CANTIDADALMUERZO {
            get {
                return this.CANTIDADALMUERZOField;
            }
            set {
                if ((this.CANTIDADALMUERZOField.Equals(value) != true)) {
                    this.CANTIDADALMUERZOField = value;
                    this.RaisePropertyChanged("CANTIDADALMUERZO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CANTIDADCENA {
            get {
                return this.CANTIDADCENAField;
            }
            set {
                if ((this.CANTIDADCENAField.Equals(value) != true)) {
                    this.CANTIDADCENAField = value;
                    this.RaisePropertyChanged("CANTIDADCENA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CANTIDADDESAYUNO {
            get {
                return this.CANTIDADDESAYUNOField;
            }
            set {
                if ((this.CANTIDADDESAYUNOField.Equals(value) != true)) {
                    this.CANTIDADDESAYUNOField = value;
                    this.RaisePropertyChanged("CANTIDADDESAYUNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CANTIDADPASAJE {
            get {
                return this.CANTIDADPASAJEField;
            }
            set {
                if ((this.CANTIDADPASAJEField.Equals(value) != true)) {
                    this.CANTIDADPASAJEField = value;
                    this.RaisePropertyChanged("CANTIDADPASAJE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DETALLE {
            get {
                return this.ID_DETALLEField;
            }
            set {
                if ((this.ID_DETALLEField.Equals(value) != true)) {
                    this.ID_DETALLEField = value;
                    this.RaisePropertyChanged("ID_DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ORDEN {
            get {
                return this.ID_ORDENField;
            }
            set {
                if ((this.ID_ORDENField.Equals(value) != true)) {
                    this.ID_ORDENField = value;
                    this.RaisePropertyChanged("ID_ORDEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTOALMUERZO {
            get {
                return this.MONTOALMUERZOField;
            }
            set {
                if ((this.MONTOALMUERZOField.Equals(value) != true)) {
                    this.MONTOALMUERZOField = value;
                    this.RaisePropertyChanged("MONTOALMUERZO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTOCENA {
            get {
                return this.MONTOCENAField;
            }
            set {
                if ((this.MONTOCENAField.Equals(value) != true)) {
                    this.MONTOCENAField = value;
                    this.RaisePropertyChanged("MONTOCENA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTODESAYUNO {
            get {
                return this.MONTODESAYUNOField;
            }
            set {
                if ((this.MONTODESAYUNOField.Equals(value) != true)) {
                    this.MONTODESAYUNOField = value;
                    this.RaisePropertyChanged("MONTODESAYUNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MONTOPASAJE {
            get {
                return this.MONTOPASAJEField;
            }
            set {
                if ((this.MONTOPASAJEField.Equals(value) != true)) {
                    this.MONTOPASAJEField = value;
                    this.RaisePropertyChanged("MONTOPASAJE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_CABECERAORDENVIATICO TBL_CABECERAORDENVIATICO {
            get {
                return this.TBL_CABECERAORDENVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CABECERAORDENVIATICOField, value) != true)) {
                    this.TBL_CABECERAORDENVIATICOField = value;
                    this.RaisePropertyChanged("TBL_CABECERAORDENVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_DETALLESOLICITUDVIATICOS TBL_DETALLESOLICITUDVIATICOS {
            get {
                return this.TBL_DETALLESOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_DETALLESOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_DETALLESOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_DETALLESOLICITUDVIATICOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_DETALLESOLICITUDVIATICOS", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_DETALLESOLICITUDVIATICOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CANTIDADPASAJEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CANTIDADVIATICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGORUTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAVIATICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_MODTARIFAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ID_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_SOLICITUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLEVIATICO> TBL_DETALLEVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_MODTARIFARIOVIATICO TBL_MODTARIFARIOVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_PERSONA TBL_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_SOLICITUDVIATICOS TBL_SOLICITUDVIATICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_TARIFAAUTOBUS TBL_TARIFAAUTOBUSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CANTIDADPASAJE {
            get {
                return this.CANTIDADPASAJEField;
            }
            set {
                if ((this.CANTIDADPASAJEField.Equals(value) != true)) {
                    this.CANTIDADPASAJEField = value;
                    this.RaisePropertyChanged("CANTIDADPASAJE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CANTIDADVIATICOS {
            get {
                return this.CANTIDADVIATICOSField;
            }
            set {
                if ((this.CANTIDADVIATICOSField.Equals(value) != true)) {
                    this.CANTIDADVIATICOSField = value;
                    this.RaisePropertyChanged("CANTIDADVIATICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGORUTA {
            get {
                return this.CODIGORUTAField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGORUTAField, value) != true)) {
                    this.CODIGORUTAField = value;
                    this.RaisePropertyChanged("CODIGORUTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAVIATICOS {
            get {
                return this.FECHAVIATICOSField;
            }
            set {
                if ((this.FECHAVIATICOSField.Equals(value) != true)) {
                    this.FECHAVIATICOSField = value;
                    this.RaisePropertyChanged("FECHAVIATICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DETALLE {
            get {
                return this.ID_DETALLEField;
            }
            set {
                if ((this.ID_DETALLEField.Equals(value) != true)) {
                    this.ID_DETALLEField = value;
                    this.RaisePropertyChanged("ID_DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_MODTARIFA {
            get {
                return this.ID_MODTARIFAField;
            }
            set {
                if ((this.ID_MODTARIFAField.Equals(value) != true)) {
                    this.ID_MODTARIFAField = value;
                    this.RaisePropertyChanged("ID_MODTARIFA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ID_PERSONA {
            get {
                return this.ID_PERSONAField;
            }
            set {
                if ((this.ID_PERSONAField.Equals(value) != true)) {
                    this.ID_PERSONAField = value;
                    this.RaisePropertyChanged("ID_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SOLICITUD {
            get {
                return this.ID_SOLICITUDField;
            }
            set {
                if ((this.ID_SOLICITUDField.Equals(value) != true)) {
                    this.ID_SOLICITUDField = value;
                    this.RaisePropertyChanged("ID_SOLICITUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_DETALLEVIATICO> TBL_DETALLEVIATICO {
            get {
                return this.TBL_DETALLEVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_DETALLEVIATICOField, value) != true)) {
                    this.TBL_DETALLEVIATICOField = value;
                    this.RaisePropertyChanged("TBL_DETALLEVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_MODTARIFARIOVIATICO TBL_MODTARIFARIOVIATICO {
            get {
                return this.TBL_MODTARIFARIOVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_MODTARIFARIOVIATICOField, value) != true)) {
                    this.TBL_MODTARIFARIOVIATICOField = value;
                    this.RaisePropertyChanged("TBL_MODTARIFARIOVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_PERSONA TBL_PERSONA {
            get {
                return this.TBL_PERSONAField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_PERSONAField, value) != true)) {
                    this.TBL_PERSONAField = value;
                    this.RaisePropertyChanged("TBL_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_SOLICITUDVIATICOS TBL_SOLICITUDVIATICOS {
            get {
                return this.TBL_SOLICITUDVIATICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_SOLICITUDVIATICOSField, value) != true)) {
                    this.TBL_SOLICITUDVIATICOSField = value;
                    this.RaisePropertyChanged("TBL_SOLICITUDVIATICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_TARIFAAUTOBUS TBL_TARIFAAUTOBUS {
            get {
                return this.TBL_TARIFAAUTOBUSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_TARIFAAUTOBUSField, value) != true)) {
                    this.TBL_TARIFAAUTOBUSField = value;
                    this.RaisePropertyChanged("TBL_TARIFAAUTOBUS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_CANTON", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_CANTON : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CODIGOCANTONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CODIGOPROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONPROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CascaronPrograIV.WCFServicio.TBL_PROVINCIA TBL_PROVINCIAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CODIGOCANTON {
            get {
                return this.CODIGOCANTONField;
            }
            set {
                if ((this.CODIGOCANTONField.Equals(value) != true)) {
                    this.CODIGOCANTONField = value;
                    this.RaisePropertyChanged("CODIGOCANTON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CODIGOPROVINCIA {
            get {
                return this.CODIGOPROVINCIAField;
            }
            set {
                if ((this.CODIGOPROVINCIAField.Equals(value) != true)) {
                    this.CODIGOPROVINCIAField = value;
                    this.RaisePropertyChanged("CODIGOPROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCIONPROVINCIA {
            get {
                return this.DESCRIPCIONPROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONPROVINCIAField, value) != true)) {
                    this.DESCRIPCIONPROVINCIAField = value;
                    this.RaisePropertyChanged("DESCRIPCIONPROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICO {
            get {
                return this.TBL_MODTARIFARIOVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_MODTARIFARIOVIATICOField, value) != true)) {
                    this.TBL_MODTARIFARIOVIATICOField = value;
                    this.RaisePropertyChanged("TBL_MODTARIFARIOVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CascaronPrograIV.WCFServicio.TBL_PROVINCIA TBL_PROVINCIA {
            get {
                return this.TBL_PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_PROVINCIAField, value) != true)) {
                    this.TBL_PROVINCIAField = value;
                    this.RaisePropertyChanged("TBL_PROVINCIA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_PROVINCIA", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TBL_PROVINCIA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CODIGOPROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONPROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CANTON> TBL_CANTONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_TARIFAAUTOBUS> TBL_TARIFAAUTOBUSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CODIGOPROVINCIA {
            get {
                return this.CODIGOPROVINCIAField;
            }
            set {
                if ((this.CODIGOPROVINCIAField.Equals(value) != true)) {
                    this.CODIGOPROVINCIAField = value;
                    this.RaisePropertyChanged("CODIGOPROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCIONPROVINCIA {
            get {
                return this.DESCRIPCIONPROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONPROVINCIAField, value) != true)) {
                    this.DESCRIPCIONPROVINCIAField = value;
                    this.RaisePropertyChanged("DESCRIPCIONPROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_CANTON> TBL_CANTON {
            get {
                return this.TBL_CANTONField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_CANTONField, value) != true)) {
                    this.TBL_CANTONField = value;
                    this.RaisePropertyChanged("TBL_CANTON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_MODTARIFARIOVIATICO> TBL_MODTARIFARIOVIATICO {
            get {
                return this.TBL_MODTARIFARIOVIATICOField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_MODTARIFARIOVIATICOField, value) != true)) {
                    this.TBL_MODTARIFARIOVIATICOField = value;
                    this.RaisePropertyChanged("TBL_MODTARIFARIOVIATICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CascaronPrograIV.WCFServicio.TBL_TARIFAAUTOBUS> TBL_TARIFAAUTOBUS {
            get {
                return this.TBL_TARIFAAUTOBUSField;
            }
            set {
                if ((object.ReferenceEquals(this.TBL_TARIFAAUTOBUSField, value) != true)) {
                    this.TBL_TARIFAAUTOBUSField = value;
                    this.RaisePropertyChanged("TBL_TARIFAAUTOBUS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServicio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarRol", ReplyAction="http://tempuri.org/IService1/InsertarRolResponse")]
        void InsertarRol(CascaronPrograIV.WCFServicio.TBL_ROLUSUARIO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarRol", ReplyAction="http://tempuri.org/IService1/InsertarRolResponse")]
        System.Threading.Tasks.Task InsertarRolAsync(CascaronPrograIV.WCFServicio.TBL_ROLUSUARIO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarPersona", ReplyAction="http://tempuri.org/IService1/InsertarPersonaResponse")]
        void InsertarPersona(CascaronPrograIV.WCFServicio.TBL_PERSONA obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarPersona", ReplyAction="http://tempuri.org/IService1/InsertarPersonaResponse")]
        System.Threading.Tasks.Task InsertarPersonaAsync(CascaronPrograIV.WCFServicio.TBL_PERSONA obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CascaronPrograIV.WCFServicio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CascaronPrograIV.WCFServicio.IService1>, CascaronPrograIV.WCFServicio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertarRol(CascaronPrograIV.WCFServicio.TBL_ROLUSUARIO obj) {
            base.Channel.InsertarRol(obj);
        }
        
        public System.Threading.Tasks.Task InsertarRolAsync(CascaronPrograIV.WCFServicio.TBL_ROLUSUARIO obj) {
            return base.Channel.InsertarRolAsync(obj);
        }
        
        public void InsertarPersona(CascaronPrograIV.WCFServicio.TBL_PERSONA obj) {
            base.Channel.InsertarPersona(obj);
        }
        
        public System.Threading.Tasks.Task InsertarPersonaAsync(CascaronPrograIV.WCFServicio.TBL_PERSONA obj) {
            return base.Channel.InsertarPersonaAsync(obj);
        }
    }
}
